# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./GeneratedFiles/ui_FlowingSpeedChanges.h \
    ./GeneratedFiles/ui_MoveTimingPoints.h \
    ./TimingPointClass/TimingPointClass.hpp \
    ./GeneratedFiles/ui_BPMNormalization.h \
    ./GeneratedFiles/ui_NxSpeedChange.h \
    ./GeneratedFiles/ui_osuSVTool.h \
    ./stdafx.h \
    ./MoveTimingPoints/MoveTimingPoints.h \
    ./FlowingSpeedChanges/FlowingSpeedChanges.h \
    ./InheritUninherit/InheritUninherit.h \
    ./BPMNormalization/BPMNormalization.h \
    ./NxSpeedChange/NxSpeedChange.h \
    ./osuSVTool.h
SOURCES += ./main.cpp \
    ./BPMNormalization/BPMNormalization.cpp \
    ./FlowingSpeedChanges/FlowingSpeedChanges.cpp \
    ./InheritUninherit/InheritUninherit.cpp \
    ./MoveTimingPoints/MoveTimingPoints.cpp \
    ./NxSpeedChange/NxSpeedChange.cpp \
    ./osuSVTool.cpp \
    ./stdafx.cpp \
    ./TimingPointClass/TimingPointClass.cpp
FORMS += ./BPMNormalization/BPMNormalization.ui \
    ./FlowingSpeedChanges/FlowingSpeedChanges.ui \
    ./InheritUninherit/InheritUninherit.ui \
    ./MoveTimingPoints/MoveTimingPoints.ui \
    ./NxSpeedChange/NxSpeedChange.ui \
    ./osuSVTool.ui
RESOURCES += osuSVTool.qrc
